/*
* generated by Xtext
*/
package org.xtext.example.mm.ui.contentassist;

import org.xtext.example.mm.ui.contentassist.AbstractCommonProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CommonProposalProvider extends AbstractCommonProposalProvider {

}
