/*
 * generated by Xtext
 */
package org.xtext.example.mm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DomainUiModule extends org.xtext.example.mm.ui.AbstractDomainUiModule {
	public DomainUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
