/*
 * generated by Xtext
 */
package org.xtext.example.mm.scoping;

import org.xtext.example.mm.scoping.CommonScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class DomainScopeProvider extends CommonScopeProvider {

}
