/*
 * generated by Xtext
 */
package org.xtext.example.mm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MetaRuntimeModule extends org.xtext.example.mm.AbstractMetaRuntimeModule {

}
