/*
 * generated by Xtext
 */
package org.xtext.example.mm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CommonUiModule extends org.xtext.example.mm.ui.AbstractCommonUiModule {
	public CommonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
